# Imports

In [55]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [56]:
import sys
import os
sys.path.append(os.path.join(os.getcwd(), os.pardir))

In [71]:
from Tools.leica_tools import RawLoader, parse_lif
from Tools.sample_tools import Sample
from Tools.db_tools import DbManager

In [72]:
parse_lif('/Users/xiangxigao/Desktop/DMi8/TECH_XG_009/TECH_XG_009.lif')

,index,name,timestamp,t_index,n_channels,bit_depth,resolution,merged
0,0,TileScan 1/oil_1_300_170 Merged,0,0,4,16,1.527160,True
1,0,TileScan 1/oil_1_300_170 Merged,1,1,4,16,1.527160,True
2,0,TileScan 1/oil_1_300_170 Merged,2,2,4,16,1.527160,True
3,0,TileScan 1/oil_1_300_170 Merged,3,3,4,16,1.527160,True
4,0,TileScan 1/oil_1_300_170 Merged,4,4,4,16,1.527160,True
5,0,TileScan 1/oil_1_300_170 Merged,5,5,4,16,1.527160,True
6,0,TileScan 1/oil_1_300_170 Merged,6,6,4,16,1.527160,True
7,0,TileScan 1/oil_1_300_170 Merged,7,7,4,16,1.527160,True
8,0,TileScan 1/oil_1_300_170 Merged,8,8,4,16,1.527160,True
9,1,TileScan 1/oil_2_300_170 Merged,0,0,4,16,1.527159,True
10,1,TileScan 1/oil_2_300_170 Merged,1,1,4,16,1.527159,True
11,1,TileScan 1/oil_2_300_170 Merged,2,2,4,16,1.527159,True
12,1,TileScan 1/oil_2_300_170 Merged,3,3,4,16,1.527159,True
13,1,TileScan 1/oil_2_300_170 Merged,4,4,4,16,1.527159,True
14,1,TileScan 1/oil_2_300_170 Merged,5,5,4,16,1.527159,True
15,1,TileScan 1/oil_2_300_170 Merged,6,6,4,16,1.527159,True
16,1,TileScan 1/oil_2_300_170 Merged,7,7,4,16,1.527159,True
17,1,TileScan 1/oil_2_300_170 Merged,8,8,4,16,1.527159,True
18,2,TileScan 2/oil_1_300_170 Merged,0,0,4,16,1.527159,True
19,2,TileScan 2/oil_1_300_170 Merged,1,1,4,16,1.527159,True
20,2,TileScan 2/oil_1_300_170 Merged,2,2,4,16,1.527159,True
21,2,TileScan 2/oil_1_300_170 Merged,3,3,4,16,1.527159,True
22,2,TileScan 2/oil_1_300_170 Merged,4,4,4,16,1.527159,True
23,2,TileScan 2/oil_1_300_170 Merged,5,5,4,16,1.527159,True
24,2,TileScan 2/oil_1_300_170 Merged,6,6,4,16,1.527159,True
25,2,TileScan 2/oil_1_300_170 Merged,7,7,4,16,1.527159,True
26,2,TileScan 2/oil_1_300_170 Merged,8,8,4,16,1.527159,True
27,3,TileScan 2/oil_2_300_170 Merged,0,0,4,16,1.527159,True
28,3,TileScan 2/oil_2_300_170 Merged,1,1,4,16,1.527159,True
29,3,TileScan 2/oil_2_300_170 Merged,2,2,4,16,1.527159,True
30,3,TileScan 2/oil_2_300_170 Merged,3,3,4,16,1.527159,True
31,3,TileScan 2/oil_2_300_170 Merged,4,4,4,16,1.527159,True
32,3,TileScan 2/oil_2_300_170 Merged,5,5,4,16,1.527159,True
33,3,TileScan 2/oil_2_300_170 Merged,6,6,4,16,1.527159,True
34,3,TileScan 2/oil_2_300_170 Merged,7,7,4,16,1.527159,True
35,3,TileScan 2/oil_2_300_170 Merged,8,8,4,16,1.527159,True
36,4,TileScan 3/oil_1_300_170 Merged,0,0,4,16,1.527159,True
37,5,TileScan 3/oil_2_300_170 Merged,0,0,4,16,1.527159,True

# Data prep

In [73]:
expID = 'TECH_XG_009'
rawloader = RawLoader(expID)
rawloader.frame_df

,droplet_size,size_range,image_index,t_index,time,condition,path
frameID,,,,,,,
0,90,5,2,0,1,HFE7500_K562_droplets_300mbaroil_150mbar,/Users/xiangxigao/Desktop/DMi8/TECH_XG_006/TEC...
1,90,5,6,0,2,HFE7500_K562_droplets_300mbaroil_150mbar,/Users/xiangxigao/Desktop/DMi8/TECH_XG_006/TEC...
2,90,5,6,1,3,HFE7500_K562_droplets_300mbaroil_150mbar,/Users/xiangxigao/Desktop/DMi8/TECH_XG_006/TEC...
3,90,5,6,2,4,HFE7500_K562_droplets_300mbaroil_150mbar,/Users/xiangxigao/Desktop/DMi8/TECH_XG_006/TEC...
4,90,5,6,3,5,HFE7500_K562_droplets_300mbaroil_150mbar,/Users/xiangxigao/Desktop/DMi8/TECH_XG_006/TEC...
5,90,5,6,4,6,HFE7500_K562_droplets_300mbaroil_150mbar,/Users/xiangxigao/Desktop/DMi8/TECH_XG_006/TEC...
6,90,5,6,5,7,HFE7500_K562_droplets_300mbaroil_150mbar,/Users/xiangxigao/Desktop/DMi8/TECH_XG_006/TEC...
7,90,5,3,0,1,RAN101_K562_droplets_300mbaroil_150mbar,/Users/xiangxigao/Desktop/DMi8/TECH_XG_006/TEC...
8,90,5,7,0,2,RAN101_K562_droplets_300mbaroil_150mbar,/Users/xiangxigao/Desktop/DMi8/TECH_XG_006/TEC...
9,90,5,7,1,3,RAN101_K562_droplets_300mbaroil_150mbar,/Users/xiangxigao/Desktop/DMi8/TECH_XG_006/TEC...
10,90,5,7,2,4,RAN101_K562_droplets_300mbaroil_150mbar,/Users/xiangxigao/Desktop/DMi8/TECH_XG_006/TEC...
11,90,5,7,3,5,RAN101_K562_droplets_300mbaroil_150mbar,/Users/xiangxigao/Desktop/DMi8/TECH_XG_006/TEC...
12,90,5,7,4,6,RAN101_K562_droplets_300mbaroil_150mbar,/Users/xiangxigao/Desktop/DMi8/TECH_XG_006/TEC...
13,90,5,7,5,7,RAN101_K562_droplets_300mbaroil_150mbar,/Users/xiangxigao/Desktop/DMi8/TECH_XG_006/TEC...

In [74]:
rawloader.channel_df
rawloader.frame_df
expID

'TECH_XG_009'

# Droplet detection

Execute a preview run of the droplet detection. An image will be saved to the exp folder in the analyses directory. 
If droplets are not well detected consider changing the droplet size estimate in setup.xlsx (re-run RawLoader API).

In [24]:
frameID = 10
sample = Sample(expID, frameID)
sample.detect_droplets(mode='sweep')
sample.visualize_droplets(channel=0,save=True)

134 droplets in frame 10 detected

Run droplet detection through all frames of the experiment. drop_register.csv will be created at the end of the process.

In [20]:
dbm = DbManager()
dbm.detect_droplets(expID, mode='sweep')

2390 droplets in frame 0 detected

2395 droplets in frame 1 detected

2405 droplets in frame 2 detected

2406 droplets in frame 3 detected

2406 droplets in frame 4 detected

2400 droplets in frame 5 detected

2399 droplets in frame 6 detected

1313 droplets in frame 7 detected

1318 droplets in frame 8 detected

1317 droplets in frame 9 detected

134 droplets in frame 10 detected

132 droplets in frame 11 detected

131 droplets in frame 12 detected

133 droplets in frame 13 detected

# Outlier detection

In [21]:
expID = 'TECH_XG_006'
dbm = DbManager()
dbm.detect_outliers(expID, model_name='outlier_v3.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

665/665 ━━━━━━━━━━━━━━━━━━━━ 88s 133ms/step

2026-09-08 15:35:27.383632: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
/Users/xiangxigao/miniforge3/envs/phenotyping/lib/python3.12/contextlib.py:158: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self.gen.throw(value)
2026-09-08 15:35:31.009615: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:31.954824: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:32.111801: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:32.292746: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:32.606853: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:32.955209: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:33.138676: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:33.310953: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:33.483758: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:33.660325: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:33.839339: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:34.082494: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:34.316431: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:34.514502: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:34.755597: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:34.948973: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:35.143760: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:35.341479: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:35.569998: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:35.721708: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:36.565468: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:36.909641: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:37.201558: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:37.482940: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:37.832896: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:38.114522: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:38.300106: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:38.465063: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:38.647602: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:38.831997: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:39.043526: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:39.304497: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:39.580886: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:39.839559: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:40.162472: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:40.451233: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:40.806829: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:41.081050: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:41.314713: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:41.554991: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2026-09-08 15:35:41.734166: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence

In [22]:
sample = Sample(expID, 0)
sample.reload_droplets()
sample.visualize_droplets(channel=0)

# Workpackage Generation

In [3]:
dbm = DbManager()
dbm.generate_wp(expID='NKIP_FA_065', exclude_query='outlier == True')

2024-09-08 22:10:21.239744: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2024-09-08 22:10:21.339381: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2024-09-08 22:10:21.549281: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2024-09-08 22:10:21.961074: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2024-09-08 22:10:22.772556: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence

# Cell counting

In [23]:
dbm = DbManager()
dbm.cell_count(expID='TECH_XG_006', model_name='cell_count_v3.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
2026-09-08 15:38:30.276478: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence

665/665 ━━━━━━━━━━━━━━━━━━━━ 344s 517ms/step

/Users/xiangxigao/miniforge3/envs/phenotyping/lib/python3.12/contextlib.py:158: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self.gen.throw(value)
2026-09-08 15:44:14.216998: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence