# Imports

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
import os
sys.path.append(os.path.join(os.getcwd(), os.pardir))

In [1]:
from Tools.leica_tools import RawLoader, parse_lif
from Tools.sample_tools import Sample
from Tools.db_tools import DbManager

EXP_DIR: /Users/xiangxigao/github/droplet-phenotyping/Experiments

2026-07-09 18:12:53.943086: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [3]:
parse_lif('/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif')

,index,name,timestamp,t_index,n_channels,bit_depth,resolution,merged
0,0,1h/Bulk_unstained Merged,2025-07-11 11:49:44,0,4,16,1.527160,True
1,1,1h/CMK_negative Merged,2025-07-11 11:57:14,0,4,16,1.527160,True
2,2,1h/CMK_positive Merged,2025-07-11 12:04:42,0,4,16,1.527160,True
3,3,1h/Bulk_stained Merged,2025-07-11 12:12:11,0,4,16,1.527159,True
4,4,2h_8h/Bulk_unstained Merged,2025-07-11 12:54:02,0,4,16,1.527159,True
5,4,2h_8h/Bulk_unstained Merged,2025-07-11 13:54:03,1,4,16,1.527159,True
6,4,2h_8h/Bulk_unstained Merged,2025-07-11 14:54:03,2,4,16,1.527159,True
7,4,2h_8h/Bulk_unstained Merged,2025-07-11 15:54:03,3,4,16,1.527159,True
8,4,2h_8h/Bulk_unstained Merged,2025-07-11 16:54:03,4,4,16,1.527159,True
9,4,2h_8h/Bulk_unstained Merged,2025-07-11 17:54:03,5,4,16,1.527159,True
10,4,2h_8h/Bulk_unstained Merged,2025-07-11 18:54:03,6,4,16,1.527159,True
11,5,2h_8h/CMK_negative Merged,2025-07-11 13:01:20,0,4,16,1.527160,True
12,5,2h_8h/CMK_negative Merged,2025-07-11 14:01:21,1,4,16,1.527160,True
13,5,2h_8h/CMK_negative Merged,2025-07-11 15:01:21,2,4,16,1.527160,True
14,5,2h_8h/CMK_negative Merged,2025-07-11 16:01:20,3,4,16,1.527160,True
15,5,2h_8h/CMK_negative Merged,2025-07-11 17:01:22,4,4,16,1.527160,True
16,5,2h_8h/CMK_negative Merged,2025-07-11 18:01:21,5,4,16,1.527160,True
17,5,2h_8h/CMK_negative Merged,2025-07-11 19:01:21,6,4,16,1.527160,True
18,6,2h_8h/CMK_positive Merged,2025-07-11 13:08:37,0,4,16,1.527160,True
19,6,2h_8h/CMK_positive Merged,2025-07-11 14:08:38,1,4,16,1.527160,True
20,6,2h_8h/CMK_positive Merged,2025-07-11 15:08:38,2,4,16,1.527160,True
21,6,2h_8h/CMK_positive Merged,2025-07-11 16:08:37,3,4,16,1.527160,True
22,6,2h_8h/CMK_positive Merged,2025-07-11 17:08:39,4,4,16,1.527160,True
23,6,2h_8h/CMK_positive Merged,2025-07-11 18:08:38,5,4,16,1.527160,True
24,6,2h_8h/CMK_positive Merged,2025-07-11 19:08:39,6,4,16,1.527160,True
25,7,2h_8h/Bulk_stained Merged,2025-07-11 13:15:54,0,4,16,1.527160,True
26,7,2h_8h/Bulk_stained Merged,2025-07-11 14:15:57,1,4,16,1.527160,True
27,7,2h_8h/Bulk_stained Merged,2025-07-11 15:15:57,2,4,16,1.527160,True
28,7,2h_8h/Bulk_stained Merged,2025-07-11 16:15:55,3,4,16,1.527160,True
29,7,2h_8h/Bulk_stained Merged,2025-07-11 17:15:57,4,4,16,1.527160,True
30,7,2h_8h/Bulk_stained Merged,2025-07-11 18:15:57,5,4,16,1.527160,True
31,7,2h_8h/Bulk_stained Merged,2025-07-11 19:15:57,6,4,16,1.527160,True

# Data prep

In [13]:
expID = 'NKIP_FA_084'
rawloader = RawLoader(expID)
rawloader.frame_df

,droplet_size,size_range,image_index,t_index,time,condition,path
frameID,,,,,,,
0,95,5,0,0,1,Bulk,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
1,85,5,1,0,1,CMKneg,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
2,90,5,2,0,1,CMKpos,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
3,85,5,3,0,1,Bulkstain,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
4,95,5,4,0,2,Bulk,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
5,85,5,5,0,2,CMKneg,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
6,85,5,6,0,2,CMKpos,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
7,85,5,7,0,2,Bulkstain,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
8,95,5,4,1,3,Bulk,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
9,85,5,5,1,3,CMKneg,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
10,85,5,6,1,3,CMKpos,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
11,85,5,7,1,3,Bulkstain,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
12,95,5,4,2,4,Bulk,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
13,85,5,5,2,4,CMKneg,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
14,85,5,6,2,4,CMKpos,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
15,85,5,7,2,4,Bulkstain,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
16,95,5,4,3,5,Bulk,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
17,85,5,5,3,5,CMKneg,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
18,85,5,6,3,5,CMKpos,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
19,85,5,7,3,5,Bulkstain,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
20,95,5,4,4,6,Bulk,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
21,85,5,5,4,6,CMKneg,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
22,85,5,6,4,6,CMKpos,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
23,85,5,7,4,6,Bulkstain,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
24,95,5,4,5,7,Bulk,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
25,85,5,5,5,7,CMKneg,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
26,85,5,6,5,7,CMKpos,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
27,85,5,7,5,7,Bulkstain,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
28,95,5,4,6,8,Bulk,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
29,85,5,5,6,8,CMKneg,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
30,85,5,6,6,8,CMKpos,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif
31,85,5,7,6,8,Bulkstain,/Volumes/T7/DMI/NKIP_FA_084/NKIP_FA_084.lif

# Droplet detection

Execute a preview run of the droplet detection. An image will be saved to the exp folder in the analyses directory. 
If droplets are not well detected consider changing the droplet size estimate in setup.xlsx (re-run RawLoader API).

In [15]:
frameID = 3
sample = Sample(expID, frameID)
sample.detect_droplets(mode='sweep')
sample.visualize_droplets(channel=0,save=True)

4586 droplets in frame 3 detected

Run droplet detection through all frames of the experiment. drop_register.csv will be created at the end of the process.

In [16]:
dbm = DbManager()
dbm.detect_droplets(expID, mode='sweep')

2761 droplets in frame 0 detected

4315 droplets in frame 1 detected

3704 droplets in frame 2 detected

4586 droplets in frame 3 detected

2776 droplets in frame 4 detected

4323 droplets in frame 5 detected

3727 droplets in frame 6 detected

4583 droplets in frame 7 detected

2766 droplets in frame 8 detected

4330 droplets in frame 9 detected

3709 droplets in frame 10 detected

4584 droplets in frame 11 detected

2754 droplets in frame 12 detected

4325 droplets in frame 13 detected

3703 droplets in frame 14 detected

4576 droplets in frame 15 detected

2742 droplets in frame 16 detected

4330 droplets in frame 17 detected

3690 droplets in frame 18 detected

4577 droplets in frame 19 detected

2719 droplets in frame 20 detected

4327 droplets in frame 21 detected

3677 droplets in frame 22 detected

4573 droplets in frame 23 detected

2717 droplets in frame 24 detected

4322 droplets in frame 25 detected

3667 droplets in frame 26 detected

4568 droplets in frame 27 detected

2716 droplets in frame 28 detected

4323 droplets in frame 29 detected

3663 droplets in frame 30 detected

4565 droplets in frame 31 detected

# Outlier detection

In [17]:
expID = 'NKIP_FA_084'
dbm = DbManager()
dbm.detect_outliers(expID, model_name='outlier_v3.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

3835/3835 ━━━━━━━━━━━━━━━━━━━━ 146s 38ms/step

2025-07-15 21:34:08.129771: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
/Users/fauberma/mambaforge/envs/phenotyping_v1/lib/python3.12/contextlib.py:155: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self.gen.throw(value)
2025-07-15 21:34:18.406745: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.080200: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.102424: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.127723: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.149006: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.171808: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.194190: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.215922: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.237441: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.261345: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.284137: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.305479: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.326848: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.349769: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.373117: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.395612: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.419210: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.441571: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.463072: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.486444: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.509504: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.530963: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.552452: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.573422: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.595087: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.616437: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.639109: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.659928: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.680865: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.701029: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.723098: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.746465: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.768453: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.790314: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.813751: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.833920: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.854758: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.875832: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.899989: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.922156: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.944019: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.965270: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:19.987955: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:20.010896: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:20.032642: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:20.055284: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:20.076774: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:20.098771: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:20.122178: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:20.143643: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:20.165015: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:20.186494: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:20.208660: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:20.229666: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:20.252377: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:20.274063: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:20.294862: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:20.316502: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:20.341141: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:20.363797: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:20.387543: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:20.409481: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:20.430599: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:20.453042: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:20.474269: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:20.968921: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:20.993111: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.016373: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.039019: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.060903: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.082610: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.103911: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.127879: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.150324: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.173506: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.198307: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.220969: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.243536: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.266181: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.286705: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.308657: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.329353: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.351184: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.372099: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.397479: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.420258: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.443012: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.464917: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.486726: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.511389: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.534591: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.556996: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.580460: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.603603: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.626287: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.650214: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.671618: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.693219: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.715092: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.737175: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.759306: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.781087: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.805446: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.826572: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.847445: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.870994: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.893798: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.915093: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.937322: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.960305: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:21.986487: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:22.012262: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:22.038787: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:22.061122: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:22.082418: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:22.104898: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:22.127347: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:22.151138: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:22.174746: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:22.199139: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:22.221566: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:22.245114: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:22.267782: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:22.290114: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:22.312553: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:22.335979: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-07-15 21:34:22.357460: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence

In [18]:
sample = Sample(expID, 0)
sample.reload_droplets()
sample.visualize_droplets(channel=0)

# Workpackage Generation

In [3]:
dbm = DbManager()
dbm.generate_wp(expID='NKIP_FA_065', exclude_query='outlier == True')

2024-09-08 22:10:21.239744: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2024-09-08 22:10:21.339381: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2024-09-08 22:10:21.549281: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2024-09-08 22:10:21.961074: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2024-09-08 22:10:22.772556: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence

# Cell counting

In [19]:
dbm = DbManager()
dbm.cell_count(expID='NKIP_FA_084', model_name='cell_count_v3.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
2025-07-15 21:34:57.983527: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence

3835/3835 ━━━━━━━━━━━━━━━━━━━━ 413s 108ms/step

2025-07-15 21:41:51.115435: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
/Users/fauberma/mambaforge/envs/phenotyping_v1/lib/python3.12/contextlib.py:155: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self.gen.throw(value)